## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
#  Tartarus Prompt Theme base on starship. If you dont want to use the custom icomoon font
#  Just delete de icons you can't see an use icons from nerd fonts.
command_timeout = 10000
format = """
[  $username$hostname ]\
(bold bg:black fg:white)\
[]\
(bold bg:cyan fg:black)\
[\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
]\
(bold bg:cyan fg:black)\
[]\
(bold bg:none fg:cyan) \
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal
[バカ](bold bg:none fg:white)\
$singularity\
$kubernetes\
$directory\
$status\
$character
"""

[fill]
symbol = " "

[username]
show_always = true
style_user = "bold bg:black fg:white"
style_root = "bold bg:black fg:white"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bg:black fg:white"
format = "[@$hostname]($style)"

[git_branch]
symbol = " "
format = " on [$symbol$branch]($style) "
style = "bold bg:cyan fg:black"

[git_commit]
style = "bold bg:cyan fg:black"

[git_state]
style = "bold bg:cyan fg:black"

[git_status]
style = "bold bg:cyan fg:black"

[time]
disabled = false
format = "[$time]($style)"
style = "bg:white fg:black"

[directory.substitutions]
"dox" = "󰈙 "
"dl" = " "
"music" = "󰝚 "
"pix" = " "
"prjcts" = "󰲋 "

[status]
disabled = false
symbol = '✗'

[line_break]
disabled = true

[character]
success_symbol = "[◉](bold cyan)"
error_symbol = "[⊘](bold red)"
vicmd_symbol = "[ ](bold yellow)"
